#! /bin/bash

if [ "$#" -lt 2 ]; then
        echo "O programa $0 requer nome do arquivo e arquivos a serem compactados"
        exit 1
fi
arquivo_saida="$1"
arquivos=("${@:2}")

todos_existem=true
for arquivo in "${arquivos[@]}"; do
        if [ ! -e "$arquivo" ]; then
                todos_existem=false
                break
        fi
done

if $todos_existem; then
        tar -czf "$arquivo_saida" "${arquivos[@]}"
        echo "Compactado com sucesso em $arquivo_saida"
else
        echo "Caminho do arquivo não existente"
fi
